version: '3.8'

services:
  # Production service for running the built app
  qidah-menu:
    image: node:20-alpine
    working_dir: /qidah-menu
    volumes:
      - .:/qidah-menu
      - /qidah-menu/node_modules
    command: sh -c "npm i && npm run build && node .output/server/index.mjs"
    ports:
      - "82:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
